# General Instruction

You must choose your own dataset.

The dataset must:

Be a supervised learning dataset (Regression or Binary Classification)

Contain at least 300 samples

Have at least 2 input features

Be in CSV format

You are NOT allowed to use Dataset or DataLoader.

You must implement everything manually.

# Question 01:

## Dataset Preparation

## Using your chosen dataset:

Load the dataset.

Perform necessary preprocessing:

Handle missing values (if any)

Encode categorical variables (if necessary)

Feature scaling (if needed)

Separate features (X) and target (y).

Convert them into NumPy arrays.

Convert them into PyTorch tensors.

Split into training and testing sets.

Clearly explain each preprocessing decision.

# **Write** Answer 01:

In [22]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [23]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [24]:
df.shape

(569, 33)

In [25]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [26]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   diagnosis                569 non-null    object
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), object(1)
memory usage: 137.9+ KB

In [28]:
X = df.iloc[:,1:]
y = df.iloc[:, 0]

In [29]:
y.head()

0    M
1    M
2    M
3    M
4    M
Name: diagnosis, dtype: object

In [30]:
X.head()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [32]:
X_train.shape

(455, 30)

In [33]:
y_train.shape

(455,)

In [34]:
# scaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# encoder
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [35]:
X_train

array([[-0.17773813,  0.36170898, -0.1389245 , ...,  1.73255014,
        -0.15622847,  1.31919139],
       [-0.59582388,  2.06212101, -0.62666424, ..., -0.90668687,
        -0.83800376, -0.97878576],
       [-0.50291594,  0.58935977, -0.50293459, ...,  0.10094292,
         0.12291029,  0.50126732],
       ...,
       [ 0.60326928, -0.74170047,  0.61696652, ...,  0.17221921,
         0.42911706,  0.33136039],
       [-0.38097426, -0.64413585, -0.4357912 , ..., -0.85477914,
        -0.87353051, -1.1080505 ],
       [ 1.98817833,  0.99820201,  1.99361721, ...,  1.495479  ,
         0.3834398 , -0.29577118]])

In [36]:
y_test

array([0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1])

In [37]:
type(X_train)

numpy.ndarray

## Data type convertion

In [38]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)

X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

In [39]:
type(X_train_tensor)

torch.Tensor

# preprocessing explanation-
**Handle missing values:** There is no missing value.

**Encode categorical variables:** Machine can not understand text lables so Encoding is done.

**Feature scaling:** Feature scalling is done to keep all values in a specific range or on similar range. So that model can performe well.

**Separate features (X) and target (y):** Feaures and target are separated so that the input and output values can be identified.

**Convert them into NumPy arrays:** They are already in Numpy array.

**Convert them into PyTorch tensors:** The data type is converted to tensor to perform pyTorch operation.

**Split into training and testing sets:** The datas are slpited in two part so that the models are not overfitted and thay do not memorize the answers.

# Question 02:

## Design a neural network using nn.Module.

### The model must contain:

Input layer

At least one hidden layer

Output layer

Suitable activation function



## Justify:

Number of hidden neurons

Choice of activation function

Print  the total number of trainable parameters.

## Write Answer 02:

In [40]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    # Hidden layer
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()

    # Output layer
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

**Number of hidden neurons** : there are 3 hidden neurons, which are in the hidden layer.

**Choice of activation function** : There are two activation function Sigmoid and ReLU. Here Sigmoid is used in hidden layer and relu is used in output layer.

In [41]:
!pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

In [48]:
# Print  the total number of trainable parameters
model = Model(X_train_tensor.shape[1])
from torchinfo import summary

summary( model, input_size =(1, X_train_tensor.shape[1]))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [1, 1]                    --
├─Linear: 1-1                            [1, 3]                    93
├─ReLU: 1-2                              [1, 3]                    --
├─Linear: 1-3                            [1, 1]                    4
├─Sigmoid: 1-4                           [1, 1]                    --
==========================================================================================
Total params: 97
Trainable params: 97
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

# Question 03:

Choose an appropriate loss function.

Choose an optimizer.

<br>

Justify your choices based on:

Regression vs Classification

Nature of the dataset

## Write Answer 03:

In [54]:
learning_rate = 0.1
loss_function = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

The Brest cancer dataset is a Binary classification prediction set so, here for loss function **"Binary Cross Entropy"** is choosed. And as optimizer **SGD(Stochastic Gradient Descent)** is chossed because it works well for small datasets and also standard optimizer for neural networks.

# Question 04:

## Implement a full training loop:

Forward pass

Loss computation

Backward pass

Parameter update

Gradient reset

### Requirements:

Train for at least 100 epochs.

Print loss every 10 epochs.

Store training loss history(You can pick your own Data Structure).

Explain clearly what happens in each step of the pipeline.

## Write Answer 04:

In [58]:
epochs = 100
model = Model(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

for epoch in range(epochs):
  # forward pass
  y_pred = model(X_train_tensor)

  # Loss computation
  loss = loss_function(y_pred, y_train_tensor.reshape(-1, 1))

  # Zero gradient
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameter update
  optimizer.step()

  #print
  if(epoch%10==0):
    print(f"{epoch}: Loss = {loss.item()}")

0: Loss = 0.9016960263252258
10: Loss = 0.6335757374763489
20: Loss = 0.42423105239868164
30: Loss = 0.2792344391345978
40: Loss = 0.20915627479553223
50: Loss = 0.17113204300403595
60: Loss = 0.14763744175434113
70: Loss = 0.13062623143196106
80: Loss = 0.11759749054908752
90: Loss = 0.10689830780029297

# Question 05:

## Evaluate the model on test data.

## For regression:

Report MSE and MAE


## For classification:

Report Accuracy

Compare training vs testing performance.

State whether the model is underfitting or overfitting.

## Write Answer 05:

In [59]:
with torch.no_grad():
  y_train_pred = model.forward(X_train_tensor)
  y_train_pred = (y_train_pred>0.9).float()
  y_train_acc = (y_train_pred == y_train_tensor).float().mean()
  print(f"Train Accuracy = {y_train_acc.item()}")

  y_test_pred = model.forward(X_test_tensor)
  y_test_pred = (y_test_pred>0.9).float()
  y_test_acc = (y_test_pred == y_test_tensor).float().mean()
  print(f"Test Accuracy = {y_test_acc.item()}")

Train Accuracy = 0.559492826461792
Test Accuracy = 0.546014130115509

The training and testing both accuracy is low. So it can be said that the model is underfitted. It is because the model is too simple that it cannot learn patterns.

# Question 06:

## Modify at least ONE of the following:

Learning rate

Number of hidden neurons

Number of epochs

### Train again and compare:

Convergence speed

Final performance

Explain how the change affected the model.

## Write Answer 06:

In [60]:
learning_rate = 0.4
loss_function = nn.BCELoss()

epochs = 100
model2 = Model(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model2.parameters(), lr = learning_rate)

for epoch in range(epochs):
  # forward pass
  y_pred = model2(X_train_tensor)

  # Loss computation
  loss = loss_function(y_pred, y_train_tensor.reshape(-1, 1))

  # Zero gradient
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameter update
  optimizer.step()

  #print
  if(epoch%10==0):
    print(f"{epoch}: Loss = {loss.item()}")

0: Loss = 0.7230916619300842
10: Loss = 0.35936781764030457
20: Loss = 0.23523291945457458
30: Loss = 0.17565514147281647
40: Loss = 0.14207428693771362
50: Loss = 0.1208723783493042
60: Loss = 0.10616444051265717
70: Loss = 0.09551596641540527
80: Loss = 0.08756749331951141
90: Loss = 0.08139607310295105

Here I have increase the learning rate. Now the learning rate is larger than previous. It means now within less steps the weight and bias will be udated faster. So comparing with the previous epoch 90 the latest epoch 90's loss is lesser, because within same epoch and larger steps the loss has been minimised.

# Question 07:


# Training Analysis

Answer the following:

Why must gradients be reset every epoch?

What happens if learning rate is too high?

What happens if learning rate is too small?

Why do we define layers inside the constructor (__init__) and not inside forward()?

## Write Answer 07:

Why must gradients be reset every epoch?

**Ans:** Gradients must be reset every epoch because pytorch accumulates it by default. If it is not cleared the gradients will be added with the previous one, which will give wrong calculation. When it is cleared the gradients only operate with the current value.

What happens if learning rate is too high?

**Ans:** The learning rate is declared to minimize the loss in a specific rate. If the learning rate is too high the optimizer may overshoot the minimum loss for taking big steps toward the local minimum.

What happens if learning rate is too small?

**Ans:** If the learning rate is too samll it may take long time to reaching the optimal solution. Or it may stuck before reahing the solution

Why do we define layers inside the constructor (__init__) and not inside forward()?

**Ans:** Layers are defined int the constructors so that the prametrs can be optimized during training. If the layers were define inside the forward method the exact layer can not be accessed because the forward method will create new layers in every forward pass