# Import Libraries

In [101]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [102]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [103]:
df.shape

(569, 33)

In [104]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [105]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Train test split

In [106]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [107]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [108]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [109]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [110]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [111]:
len(df.columns)

31

In [112]:
len(X_train) + len(X_test)

569

In [113]:
X_train

array([[ 0.70741386, -0.12005282,  0.66737821, ...,  0.45726914,
        -0.15013872, -0.64759639],
       [-0.39696733, -0.30665811, -0.39933956, ..., -0.5788888 ,
        -0.20003638, -0.28233895],
       [-0.2166602 , -1.54058557, -0.29720266, ..., -1.44808147,
        -1.02415257, -1.19601192],
       ...,
       [-0.16594882, -0.69619664, -0.21263331, ..., -0.46058371,
        -0.15657712, -0.35433172],
       [-0.52938038, -0.42795154, -0.5035192 , ..., -0.29331431,
        -0.1356523 ,  1.44442887],
       [-1.47261207, -0.09672716, -1.3439016 , ..., -0.04301845,
         0.37298192,  1.11093294]])

In [114]:
y_train

array([1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0])

In [115]:
X_train

array([[ 0.70741386, -0.12005282,  0.66737821, ...,  0.45726914,
        -0.15013872, -0.64759639],
       [-0.39696733, -0.30665811, -0.39933956, ..., -0.5788888 ,
        -0.20003638, -0.28233895],
       [-0.2166602 , -1.54058557, -0.29720266, ..., -1.44808147,
        -1.02415257, -1.19601192],
       ...,
       [-0.16594882, -0.69619664, -0.21263331, ..., -0.46058371,
        -0.15657712, -0.35433172],
       [-0.52938038, -0.42795154, -0.5035192 , ..., -0.29331431,
        -0.1356523 ,  1.44442887],
       [-1.47261207, -0.09672716, -1.3439016 , ..., -0.04301845,
         0.37298192,  1.11093294]])

In [116]:
type(y_train)

numpy.ndarray

In [117]:
type(y_test)

numpy.ndarray

# Numpy Array to tensors

In [118]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

#change dtype
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

#numpy to tensor
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

# y_test_tensor = torch.from_numpy(y_test)

/tmp/ipykernel_233/3826779354.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
/tmp/ipykernel_233/3826779354.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
/tmp/ipykernel_233/3826779354.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
/tmp/ipykernel_233/3826779354.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

In [119]:
type(X_train_tensor)

torch.Tensor

# Dataset and Dataloader

In [120]:
from torch.utils.data import Dataset,DataLoader

In [121]:
class CustomDataset(Dataset):
  def __init__( self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index], self.labels[index]

In [122]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [123]:
len(train_dataset)

455

In [124]:
train_dataset[2]

(tensor([-0.2167, -1.5406, -0.2972, -0.2863, -1.5721, -1.3112, -1.1099, -1.1747,
         -1.6298, -1.2964, -0.6501, -0.9389, -0.6671, -0.4404, -1.2014, -1.2038,
         -0.9717, -1.3838, -0.6865, -0.8187, -0.3013, -1.4310, -0.3834, -0.3494,
         -1.7990, -1.2586, -1.2712, -1.4481, -1.0242, -1.1960]),
 tensor(0.))

#loader

In [125]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32,shuffle=True)

# Defining the Model

In [126]:
X_train.shape[1]

30

In [127]:
import torch.nn as nn

In [128]:
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [129]:
torch.rand(30,1)

tensor([[0.2395],
        [0.0720],
        [0.1601],
        [0.8482],
        [0.3472],
        [0.2603],
        [0.8057],
        [0.1375],
        [0.2887],
        [0.7969],
        [0.0725],
        [0.9922],
        [0.8782],
        [0.6990],
        [0.8776],
        [0.0488],
        [0.2766],
        [0.5531],
        [0.3937],
        [0.3782],
        [0.1300],
        [0.8719],
        [0.6410],
        [0.2485],
        [0.6729],
        [0.7778],
        [0.2762],
        [0.4980],
        [0.2365],
        [0.8500]])

# Parameters

In [130]:
X_train_tensor.shape[1]

30

In [131]:
learning_rate = 0.1
epochs = 25

In [132]:
loss_function = nn.BCELoss()

In [133]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [134]:
model = MySimpleNN(X_train_tensor.shape[1])

In [135]:
model.parameters()

In [136]:
X_test_tensor.dtype

torch.float32

In [137]:
model.linear.weight.dtype

torch.float32

In [138]:
y_train_tensor.dtype

torch.float32

In [139]:
model.parameters()

# Training Pipeline
### Using dataset and dataloader with Mini batch

In [140]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop

for epoch in range(epochs):

  for batch_feature,batch_labels in train_loader:
    #forward pass
    y_pred = model(batch_feature)
    #Loss calculate
    loss = loss_function(y_pred,batch_labels.reshape(-1,1))

    #zero gradient
    optimizer.zero_grad()
    #backward pass
    loss.backward()

    #parameter update
    optimizer.step()

  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.2012106329202652
 2 , Loss = 0.1759171187877655
 3 , Loss = 0.5221825838088989
 4 , Loss = 0.11041789501905441
 5 , Loss = 0.10307604819536209
 6 , Loss = 0.15833090245723724
 7 , Loss = 0.2510429322719574
 8 , Loss = 0.030360886827111244
 9 , Loss = 0.0718526840209961
 10 , Loss = 0.007829146459698677
 11 , Loss = 0.06815049797296524
 12 , Loss = 0.04285183176398277
 13 , Loss = 0.008853266946971416
 14 , Loss = 0.11903135478496552
 15 , Loss = 0.007843063212931156
 16 , Loss = 0.10347871482372284
 17 , Loss = 0.17421677708625793
 18 , Loss = 0.014563341625034809
 19 , Loss = 0.016018753871321678
 20 , Loss = 0.22127248346805573
 21 , Loss = 0.088913194835186
 22 , Loss = 0.08631285279989243
 23 , Loss = 0.020684702321887016
 24 , Loss = 0.02753506414592266
 25 , Loss = 0.0014930941397324204

# Training pipeline version 2
### For Mini batch GD here manually slicing the tensor to make batches.

In [141]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop
batch_size = 32
epoch = 25
n_sample = len(X_train_tensor)

for epoch in range(epochs):
  for start_indx in range(0, n_sample, batch_size):
    end_indx = start_indx + batch_size

    # print(f" Start index {start_indx}, end indx {end_indx}\n")

    X_batch = X_train_tensor[start_indx:end_indx]
    y_batch = y_train_tensor[start_indx:end_indx]

    #forward pass
    y_pred = model(X_batch)
    loss = loss_function(y_pred, y_batch.reshape(-1,1))

    #upate step
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.1664494425058365
 2 , Loss = 0.10468084365129471
 3 , Loss = 0.07786397635936737
 4 , Loss = 0.06253798305988312
 5 , Loss = 0.05252164602279663
 6 , Loss = 0.04543209448456764
 7 , Loss = 0.04013925790786743
 8 , Loss = 0.03603294491767883
 9 , Loss = 0.03275275602936745
 10 , Loss = 0.030071577057242393
 11 , Loss = 0.027838746085762978
 12 , Loss = 0.025950338691473007
 13 , Loss = 0.024332331493496895
 14 , Loss = 0.0229304488748312
 15 , Loss = 0.02170402929186821
 16 , Loss = 0.020622000098228455
 17 , Loss = 0.01966024562716484
 18 , Loss = 0.01879965327680111
 19 , Loss = 0.018025005236268044
 20 , Loss = 0.017323916777968407
 21 , Loss = 0.01668637990951538
 22 , Loss = 0.016103986650705338
 23 , Loss = 0.015569806098937988
 24 , Loss = 0.015078042633831501
 25 , Loss = 0.014623739756643772

# Model Evaluation (old)

In [142]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.6061865091323853

#Model Evaluation Better version

In [143]:
y_pred.shape

torch.Size([114, 1])

In [144]:
batch_labels.shape

torch.Size([7])

In [145]:
model.eval()  #evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float()

    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()

    accuracy_list.append(batch_accuracy)


overall_accuracy = sum(accuracy_list) / len(accuracy_list)

print("Overall accuracy", overall_accuracy)

Overall accuracy 0.9921875

In [146]:
accuracy_list

[0.96875, 1.0, 1.0, 1.0]

# Summary

In [147]:
X_train_tensor.shape

torch.Size([455, 30])

In [148]:
!pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

In [149]:
from torchinfo import summary

In [150]:
summary(model, input_size = (455,30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================